config/routes.rb
Pga::Application.routes.draw do

  root to: 'players#index'
  resources :players
  resources :tournaments
  resources :users, only: [:new, :create, :index]
  delete '/users/new' => 'authentications#destroy'

  resources :authentications, only: [:new, :create]

  get 'authentications/new' => 'authentications#new'
  post 'authentications' => 'authentications#create'
  get 'authentications/:id' => 'authentications#show'
  delete 'authentications' => 'authentications#destroy'
  put 'authentications/:id' => 'authentications#update'

end

app/models/player.rb
class Player < ActiveRecord::Base
	require 'bcrypt'
	
	
	has_many :points
	has_many :tournaments, through: :points, class_name: "Tournament"
end
 
 

app/models/point.rb
class Point < ActiveRecord::Base
	require 'bcrypt'
	
  belongs_to :player
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
	require 'bcrypt'

	has_many :points
	has_many :players, through: :points, class_name: "Player"
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'bcrypt'

	has_many :Users

	validates :email, presence: true
	validates :email, uniqueness: { case_sensitive: false }
	validates :password, confirmation: true

	def userdef
		@email = email
		@salt = salt
		@hashed_password = hashed_password
	end

	attr_accessor :password, :password_confirmation

	before_save :hash_password

	def authenticate(password)
		self.hashed_password == 
		BCrypt::Engine.hash_secret(password self.salt)
	end

	private
	def hash_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.hashed_password = 
			BCrypt::Engine.hash_secret(password, self.salt)
			password = password_confirmation = nil
			end
		end
	end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find_by(id: session[:user_id])
  	end
end

	def authenticate_user
		redirect_to authentications_url unless current_user
	end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
	before_action :authenticate_user, only: [:destroy]

	def new
		#User logged in?
		if current_user #Already logged in. Can't create same user.
			redirect_to root_url
		else
			@user = User.new
		end
	end

	def create
		if user = User.find_by(email: params[:user][:email])
			#authenticate user
			if user.authenticate(params[:user][:password]) && if session[:user_id] = user.user_id 
				redirect_to root_url
			else
				flash.now.alert = "There was something wrong with your login. Please try again."
				redirect_to root_url
			end
		end
	end
end

	def destroy
		session[:user_id] = nil
		redirect_to root_url,
		notice: "Successfully signed out."
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

	def index
		@players = Player.all
	end

	def new
		@player = Player.new
	end



	def show
		@player = Player.find(params[:id])
	end

	def create
		@player = Player.new(params[:player].permit(:name))
		@points = Point.new(amount: params[:player][:points])
		@player.points << @points
		@tournaments = Tournament.new(params[:player][:tournaments])
		@player.tournaments << @tournaments
		# STRONG PARAMS HERE
		@player.save
		redirect_to players_path
	end

	def edit
		@player = Player.find(params[:id])

	end

	def update
		@player = Player.find(params[:id])
		if @player.update_attributes(params[:player].permit(:name))
			redirect_to @player
		else 
			render "edit"
		end
	end

	def destroy
		Player.find(params[:id]).destroy
		redirect_to players_url
	end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController

	def index
		@points = Point.all
	end

	def new
		@point = Point.new
	end

	def show
		@point = Point.find(params[:id])
	end

	def create
		@point = Point.new(params[:point].permit(:amount))
		@point.save
		redirect_to points_path
	end

	def edit
		@point = Point.find(params[:id])

	end

	def update
		@point = Point.find(params[:id])
		if @point.update_attributes(params[:player].permit(:name))
			redirect_to @point
		else 
			render "edit"
		end
	end

	def destroy
		Point.find(params[:id]).destroy
		redirect_to points_url
	end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

	def index
		@tournaments = Tournament.all
	end

	def new
		@tournament = Tournament.new
	end

	def show
		@tournament = Tournament.find(params[:id])
	end

	def create
		player_name = nil
		params[:incoming].each_line do |line|
			next if line.length < 31
			# Event tour week year finish "rank points" weight "adjusted points" rank

			cells = line.split("\t")
			# Take out the first entry if it's just a blank string
			cells.shift if cells[0] == ""
			next if cells[0] == ""
			if cells[0].index("Official World Golf Ranking for ") == 0
				player_name = cells[0][32..cells[0].length-1]
			else
				weight = cells[12].to_f
				next if weight < 0.1

				# Find the event name and the weight
#				puts cells[0] + " " + weight.to_s
				t = Tournament.find_or_initialize_by(name: cells[0])
				# Test to see if the weight isn't consistent
				if !t.new_record? && t.weight != weight
					puts "********** Weight difference!!! " + t.name + " old: " + t.weight.to_s + " new: " + weight.to_s
				else
					t.weight = weight
					t.save
				end
				if player_name
					# Cool, we can associate this player with their score and such
					p = Player.find_or_create_by(name: player_name)
					# And put their points in for this tournament
					pt = Point.find_or_initialize_by(player_id: p.id, tournament_id: t.id)
					if pt.new_record?
						pt.amount = cells[10].to_f
						puts "^^^^^^^^^ " + cells[10]
						pt.save
					end
				end
			end
		end

		# @tournament = Tournament.new(params[:tournament].permit(:name))
		# @tournament.save
		redirect_to tournaments_path
	end

	def edit
		@tournament = Tournament.find(params[:id])

	end

	def update
		@tournament = Tournament.find(params[:id])
		if @tournament.update_attributes(params[:tournament].permit(:name))
			redirect_to @tournament
		else 
			render "edit"
		end
	end

	def destroy
		Tournament.find(params[:id]).destroy
		redirect_to tournaments_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def show
		@users = User.find(params[:id])
	end

	def create
		@user = User.create(params[:user].permit(:email, :password, :password_confirmation))
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url
		else
			redirect_to action:"new"
		end
	end

	def destroy
		User.find(params[:id]).destroy
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pga</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar">
		<a href="/"><div class="icon"></div></a>
		<!-- if statement for Login vs. Logged in -->
		<% if current_user %>

		<a href="/"><div class="pga_logo"></div></a>
		<div id="home_logout">
			<div class="login">
				<h1 class="logged"><%= current_user[:email] %></h1>
				<%= button_to "Log out", "/users/new", method: :delete, id: 'logoutbutton' %>
			</div>
		</div>

		<% else %>
		<!-- else statement for Login vs. Logged in -->
		<div class="login">
			<%= form_for User.new, {url:"/authentications", method:"post"} do |u| %>
			<p>
				<%= u.text_field :email, placeholder: "email" %>
				<%= u.password_field :password, placeholder: "password" %>
				<%= button_to "login" %>
			</p>
			<% end %>
		</div>
		<% end %>
		<!-- end if statement -->
	</div>





<%= yield %>

</body>
</html>

app/views/players/index.html.erb
<%= session[:user_id] %>
<h1>PGA World Rankings</h1>
<h2>Stats for the 2013 season</h2>

<table>
    <tr>
      <th>Player Name</th>
      <th>Points</th>
    </tr>

    <tr>
      <% @players.each do |player| %>
      <td><%= player.name %></td>
      <% player.points.each do |point| %>
      <td><%= point.amount %></td>
      <% end %>
      <td><%= player.tournament %></td>
      
      <td><%= button_to "delete", { action: "destroy", id: player.id},
      {method: :delete, data:{confirm: "Are you sure?"}}%></td>
      <td><%= button_to "edit", edit_player_path(player) %></td>
    </tr>


    <% end %>
</table>

app/views/players/new.html.erb
<h1>Add Players</h1>

<%= form_for @player do |p| %>

<p>
		<%= p.label :name%>
		<%= p.text_field :name %>
</p>

<p>
		<%= p.label :points, "Points"%>
		<%= p.text_field :points %>
</p>

<p>
		<%= p.label :tournament, "Events"%>
		<%= p.text_field :tournament %>
</p>



<p>
<%= p.submit%>
</p>

<%end%>

app/views/tournaments/edit.html.erb
<h1>Edit Tournament</h1>

<%= form_for :tournament do |t|%>
<p>
		<%= t.label :name%>
		<%= t.text_field :name %>
</p>

<p>
		<%= t.label :weight, "Weight"%>
		<%= t.text_field :weight %>
</p>

<p>
		<%= t.label :rank, "Rank"%>
		<%= t.text_field :rank %>
</p>

<p>
	<%= t.submit :Change %>
</p>



<%end%>

app/views/tournaments/index.html.erb
<h1>2013 Tournaments</h1>

<%= form_for :tournament do |t|%>
<p>
		<%= t.label :name%>
		<%= t.text_field :name %>
</p>

<p>
		<%= t.label :points, "Points"%>
		<%= t.text_field :points %>
</p>

<!-- <p>
		<%= t.label :rank, "rank"%>
		<%= t.text_field :rank %>
</p> -->

<p>
	<%= t.submit :Change %>
</p>



<%end%>

app/views/tournaments/new.html.erb
<h1>Add Tournaments</h1>

Paste in whatever from:
<a href="http://www.officialworldgolfranking.com/players/bio.sps?ID=6430&name=Adam&Rank=2&TotalPts=393.43072">Official world golf ranking, some players' bio -- a guy named Adam</a><br />

<br />

<%= form_for @tournament do |t|%>
	<%= text_area_tag :incoming, "", size:"50x30" %>
	<%= t.submit :Add%>
<%end%>

app/views/users/_form.html.erb
<%= form_for User.new do |u| %>

<div class='container_signup signup'>
	<%=u.text_field :email, placeholder: 'email' %><br />
	<%=u.password_field :password, placeholder: 'password' %><br />
	<%=u.text_field :password_confirmation, placeholder: 'confirm password' %><br />
	<div class='center'><%= u.submit %><div>
	</div>

	<% end %>

app/views/users/new.html.erb
<%= form_for @user do |u| %>

<div class='container'>
	<%=u.text_field :email, placeholder: 'email' %><br />
	<%=u.password_field :password, placeholder: 'password' %><br />
	<%=u.text_field :password_confirmation, placeholder: 'confirm password' %><br />
	<div class='center'><%= u.submit %><div>
	</div>

	<% end %>